version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: DockerFile   # or rename to Dockerfile and drop this line
    volumes:
      - .:/var/www
    working_dir: /var/www
    ports:
      - "8000:80"
    networks:
      - laravel
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: my_custom_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: laravel_phpmyadmin2
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: laravel
      PMA_PASSWORD: laravel
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata:
